### ISSUE TITLE
Not compatible with ESP8266 or ESP32

### ISSUE THREAD

**Issue by robyxp** [0015/TP_Arduino_DigitalRain_Anim#2]
I 0015, I have seen your work on youtube and I have seen that it is very beautiful. But I'm testing it on ESP8266 and I think it's not compatible, I get several errors.
Will you make a version compatible with ESP in the future?
Thank you very much

**Comment by 0015** [comment]
@robyxp Sorry I haven't been able to confirm enough that it works on the ESP8266. There will be an update this month, so I'll check again.
