### ISSUE TITLE
I have used your library in my ESP32_8BIT_CVBS library 

### ISSUE THREAD

**Issue by riraosan** [0015/TP_Arduino_DigitalRain_Anim#5]
Hi @0015 Eric

I am riraosan
I have reprinted your library as a sample program in my project ESP32_8BIT_CVBS.
I needed to avoid link errors as a test project. For that reason, I have put your library in one file with some modifications to work with ESP32_8BIT_CVBS.
If you like you can refer to it
I appreciate your contribution. Thanks.

https://github.com/riraosan/ESP32_8BIT_CVBS/tree/master/sample/02_Sprite/MatrixRain

**Comment by 0015** [comment]
@riraosan That's great!!! Thanks for letting me know.
