### ISSUE TITLE
Compiler warnings about comparisons with incompatible types

### ISSUE THREAD

**Issue by SheetLightning** [0015/TP_Arduino_DigitalRain_Anim#8]
I was getting a couple of warnings about comparisons with incompatible types so I changed the following lines in DigitalRainAnimation.hpp:

`30 uint32_t timeFrame;            //time frame for drawing`

`76 void lineUpdate(unsigned int lineNum) {`

`86 void lineAnimation(unsigned int lineNum) {`

This gets rid of the warnings.

Thanks for publishing this project.

**Comment by 0015** [comment]
Thank you. I will apply it in the next update.
